[package]
name = "push-errors"
version = "0.1.0"
authors = ["jrconlin <me+crypt@jrconlin.com>"]
edition = "2018"
license = "MPL-2.0"

[dependencies]
failure = "0.1.5"
failure_derive = "0.1.5"
openssl = "0.10"
rusqlite = "0.16.0"
lazy_static ="1.2"
ffi-support = {path = "../../support/ffi"}
url = "1.7.2"
